name: jChat
main: name.richardson.james.jchat.jChat
author: James Richardson (grandwazir)
description: Simple chat prefix/suffix plugin for use with BukkitPermissions.
website: https://github.com/grandwazir/jChat 
softdepend: [PermissionsBukkit]
version: 1.3.3
commands:
  jchat:
    description: The root jChat command
    usage: /jchat <refresh>
