name: jChat
main: name.richardson.james.jchat.jChat
author: James Richardson (grandwazir)
description: Simple chat prefixes and suffixes.
website: https://github.com/grandwazir/jChat 
softdepend: [PermissionsBukkit]
version: 1.4.0
commands:
  jchat:
    description: The root jChat command
    usage: /jchat <refresh>
