name: jChat
main: name.richardson.james.bukkit.jchat.jChatPlugin
author: James Richardson (grandwazir)
description: Simple chat prefixes and suffixes.
website: https://github.com/grandwazir/jChat 
softdepend: [PermissionsBukkit]
version: ${project.version}
commands:
  jchat:
    description: The root jChat command
    usage: /jchat <refresh>
