name: jChat
version: ${project.version}
description: Simple chat prefixes and suffixes.
author: James Richardson (grandwazir)
website: https://github.com/grandwazir/jChat
main: name.richardson.james.bukkit.jchat.jChat
softdepend: [PermissionsBukkit]
commands:
  jchat:
    description: The root jChat command
    usage: There was an error enabling jChat.